# Generated by Django 3.1.7 on 2021-03-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cube',
            name='size',
            field=models.CharField(default=1, max_length=255, verbose_name='Длина стороны'),
            preserve_default=False,
        ),
    ]
