# Generated by Django 3.1.7 on 2021-04-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20210406_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=22, max_length=255, verbose_name='Цвет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='Длина стороны'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='Вес'),
            preserve_default=False,
        ),
    ]
